import { formatGameTime } from '@/lib/format-time'

interface Game {
  id: string
  scheduledAt: string
  court: string | null
  weekNumber: number | null
  homeTeamName: string
  awayTeamName: string
}

interface Props {
  games: Game[]
  date: string        // YYYY-MM-DD (display only)
  leagueName: string
  orgName: string
  timezone: string
}

export function DailyScheduleSheet({ games, date, leagueName, orgName, timezone }: Props) {
  // Format the date as a long readable string for the header
  const dateDisplay = new Intl.DateTimeFormat('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
    timeZone: timezone,
  }).format(new Date(`${date}T12:00:00`))  // noon to avoid DST edge

  return (
    <div className="font-sans text-black">
      {/* Header */}
      <div className="flex items-start justify-between mb-1">
        <div>
          <p className="text-xs text-gray-500 uppercase tracking-wide">{orgName}</p>
          <h1 className="text-xl font-bold leading-tight">{leagueName}</h1>
        </div>
        <div className="text-right">
          <p className="text-base font-semibold">{dateDisplay}</p>
          <p className="text-xs text-gray-500">{games.length} game{games.length !== 1 ? 's' : ''}</p>
        </div>
      </div>

      <hr className="border-black mb-3" />

      {/* Table */}
      <table className="w-full text-sm border-collapse">
        <thead>
          <tr className="border-b-2 border-black">
            <th className="text-left py-1.5 pr-4 font-semibold w-16">Time</th>
            <th className="text-left py-1.5 pr-4 font-semibold w-12">Court</th>
            <th className="text-left py-1.5 pr-4 font-semibold">Home Team</th>
            <th className="text-center py-1.5 px-4 font-semibold w-36">Score</th>
            <th className="text-right py-1.5 pl-4 font-semibold">Away Team</th>
          </tr>
        </thead>
        <tbody>
          {games.map((game) => {
            const { time } = formatGameTime(game.scheduledAt, timezone)
            return (
              <tr key={game.id} className="border-b border-gray-300">
                <td className="py-2.5 pr-4 font-medium tabular-nums">{time}</td>
                <td className="py-2.5 pr-4 text-gray-600">{game.court ?? '—'}</td>
                <td className="py-2.5 pr-4 font-medium">{game.homeTeamName}</td>
                <td className="py-2.5 px-4">
                  <div className="flex items-center justify-center gap-2">
                    <span className="inline-block w-10 h-8 border-2 border-black rounded" />
                    <span className="font-bold text-base">—</span>
                    <span className="inline-block w-10 h-8 border-2 border-black rounded" />
                  </div>
                </td>
                <td className="py-2.5 pl-4 text-right font-medium">{game.awayTeamName}</td>
              </tr>
            )
          })}
          {games.length === 0 && (
            <tr>
              <td colSpan={5} className="py-8 text-center text-gray-400 italic">No games scheduled for this day.</td>
            </tr>
          )}
        </tbody>
      </table>

      {/* Referee signature line */}
      <div className="mt-8 pt-4 border-t border-gray-400">
        <div className="flex items-end gap-8">
          <div className="flex-1">
            <p className="text-xs text-gray-500 mb-1">Referee (print name)</p>
            <div className="border-b border-black h-6" />
          </div>
          <div className="flex-1">
            <p className="text-xs text-gray-500 mb-1">Referee signature</p>
            <div className="border-b border-black h-6" />
          </div>
          <div className="w-28">
            <p className="text-xs text-gray-500 mb-1">Date</p>
            <div className="border-b border-black h-6" />
          </div>
        </div>
      </div>

      {/* Footer */}
      <p className="text-[10px] text-gray-400 text-center mt-6">
        {orgName} · {leagueName} · Generated by Fieldday
      </p>
    </div>
  )
}
